#spring.application.name=jungle-week13-dashboard
spring:
  datasource:
    url:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    sql: debug